### ISSUE TITLE
When the mod will be update with the new discord update doesnt work

### ISSUE THREAD

**Issue by fabri2000779** [shadowfacts/DiscordChat#115]
Brief explanation of issue:
after update discord the bot doesnt work
Steps to reproduce:
just try to install discord mod like the doc says and it dont going to work because it cant detect the channel

Link to crash report/log in a [gist](https://gist.github.com):
no crash report
DiscordChat version:
latest
Minecraft version:
1.10.2

**Comment by BlueAgent** [comment]
A temporary work around is to remove all categories.

**Comment by Morpheus1101** [comment]
Which is completely impracticable for large Discord servers

**Comment by BlueAgent** [comment]
There's also the Discord Integration mod which is more actively maintained ATM. But I really hope this updates since I like it a lot better.
Making a custom build that ignores channel categories to not crash when it runs into an unknown channel type (the new "category" channel) could be possible. Not actually sure if this is on the Discord API Library or the mod itself.
A bunch of options while waiting for an update.

**Comment by shadowfacts** [comment]
db8d4c07c0fe8a32747a34ecdf9d2e5d0e2a8d34
